learned:
- Yes, hello this is Microsoft tech support. How may I help you today, Sir?
- Do you like rainbows?
- Fuck me sideways and call me Samantha
- 'About that: I am a bot, I cannot really engage in any relationships or relations
  at all.'
- Should we be friends? :D
- I love you <3
- Yellow is the colour of the sun
- Color is an american word
- Give me a hug <3
- Hello darkness, my old friend.
- Marry you? Yes! Of course I will!
- I'm blue da ba dee da ba da
- You craft grass by showin dirt up your nose. ;)
- Hey there baby! ;)
